version: '3.8'

services:
  traefik:
    ports:
      - "8999:80"
    command:
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
      - "--ping=true"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=stg_app-net"
      - "--providers.swarm.constraints=Label(`com.docker.stack.namespace`,`stg`)"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--log.level=INFO"
    deploy:
      replicas: 1

  frontend:
    deploy:
      replicas: 2

  backend:
    deploy:
      replicas: 2